# Generated by Django 4.0.4 on 2022-07-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart_date_wishlist_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
